### ISSUE TITLE
you can not add a group

### ISSUE THREAD

**Issue by timtimeshock** [phpbb-extensions/autogroups#144]
Does not work on phpbb version 3.2.5 cz, can not add a group
screen1
http://timeshock0.sweb.cz/autogroups%201.png
screen2
http://timeshock0.sweb.cz/autogroups2.png

**Comment by VSEphpbb** [comment]
It works, you just don't have any new groups yet (it does not work with the default groups that come with phpBB, only with new custom groups you create).

**Comment by timtimeshock** [comment]
It's all right now. Thank you

**Comment by timtimeshock** [comment]
It's all right now. Thank you

so 5. 1. 2019 v 16:41 odesílatel Matt Friedman <notifications@github.com>
napsal:
