### ISSUE TITLE
Check membership when member visits

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/autogroups#166]
Use an event to run the membership check for a specific user when they visit, so they can be immediately added or removed from a user group based on the length of their membership. 

Currently this is just checked by cron jobs and after registering. It should also be checked when the user is logged in or becomes active on the board.

**Comment by TrekRed** [comment]
Hello. How to make the autogroup automatically add users, otherwise you have to constantly synchronize data?
![Cron](https://user-images.githubusercontent.com/101043135/156918862-89bc5e25-2f9f-4068-9a65-4468ff3ed46a.png)
