### ISSUE TITLE
Inactive User auto group

### ISSUE THREAD

**Issue by iMattPro** [phpbb-extensions/autogroups#37]
Inactive User type class ? Was requested by a user though not part of our original plans. Add users after a period of inactivity to a group.

Possible selectors:
`user_lastvisit` is a timestamp reflecting the last time a user logged in. This could be used in cron to add users. But it should probably also be called at login to remove a user (since they've just become active again). If the value is 0, it means the user has never logged in.

`user_inactive_time` is a timestamp set when a user account is deactivated (or just never activated). I'm not sure if this is worth including since it refers to accounts that most likely were just never activated in the first place, and never did anything. If the value is 0, it means the user account is activated. The timestamp is only recorded when an account requiring activation is created, or if an Admin deactivates an account.

**Comment by rxu** [comment]
Would this involve also deactivating users? Personally I'm not sure about that as this is a kind of administrator work and exseeds the ext functionality a bit (just moving users between groups).

**Comment by VSEphpbb** [comment]
No, just adding them to a special group. I'm still not so sure I see the point of this one, but one person mentioned a request for it, so it's not really on our list of things to do. This issue is to keep track of it in case we decide it is worth doing.
