### ISSUE TITLE
If you have many groups, they do not fit it standard VARCHAR(255) config_value

### ISSUE THREAD

**Issue by hyperreal-info** [phpbb-extensions/autogroups#47]
If you have many groups, they do not fit it standard VARCHAR(255) config_value, when you set which groups do not qualify for autogroup. I had to extend it to VARCHAR(512).

**Comment by VSEphpbb** [comment]
There is no "groups that do not qualify for autogroup". That setting is to prevent a users default group from being switched to their new group. So an Admin still looks like an admin after being added to some other group.

You can default-change exempt a little over 20 user groups. If you have that many groups that need default state exemption, perhaps Auto Group functionality is not right for your board, as the exemptions are only intended for Admin and moderator groups, plus any super special groups that must remain as a users default.

The point of this extension is to move users into new groups based on achievements. Only moderators and admins, who can still be moved into other groups, really need to still have their group default status preserved.

**Comment by hyperreal-info** [comment]
I do not see any reason why owning many groups and exempting some may disqualify me from using autogroups. It simply must be solved in a different way, for example storing that data in an other table.

**Comment by VSEphpbb** [comment]
We will look into it.

**Comment by VSEphpbb** [comment]
In the meantime @hyperreal-info you should revert those changes you made and uninstall this extension. This extension is still in development and not to be used on any boards.
