### ISSUE TITLE
Option to exempt from autogrouping

### ISSUE THREAD

**Issue by rxu** [phpbb-extensions/autogroups#49]
Currently we have an option to exempt user groups from losing their default state if autogroup is set to bacome the default one.
There can be the cases when administrator wants individual users (user groups) to be exempted from autogrouping at all eventhough they (their members) comply existing autogroups rules.

We could want to add this option to the extension, although I'm not sure if this option should be per-group-based or global-based, or both.

**Comment by VSEphpbb** [comment]
That could actually be a pretty major task to work out. For example, you'd probably need another ACP section to name users and select groups to exempt them from. And I'm pretty sure it will add a lot more complexity (queries and such) to an already query heavy process to find and filter out these users every time AG runs.

For now, I'm fine taking the position that using Auto Groups means you expect to totally automate the movement of users in/out of certain groups, and the responsible way to use it is with groups and under conditions that you shouldn't need to get "managerial" with in a manual way anyways.

If anybody wants to work on this, if they know how to do it efficiently, feel free. It is worth doing but only if it can be done in a way that doesn't over-complexify the code, execution and user experience.
